version: '3'
services:
  api:
    build: .
    image: ${REGISTRY}/${IMAGENAME}:latest
    ports:
      - "8000:8000"
   # command: pytest -v
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - GRAPHQL_URL=${GRAPHQL_URL}
      - GRAPHQL_SECRET=${GRAPHQL_SECRET}
      - AQUA_DB=${AQUA_DB}
      - TEST_KEY=${TEST_KEY}
      - FAIL_KEY=${FAIL_KEY}
      - KEY_VAULT=${KEY_VAULT}
      - MODAL_WEBHOOK_TOKEN=${MODAL_WEBHOOK_TOKEN}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
