"""add morpheme tokenizer tables

Revision ID: 15a13c99aaf1
Revises: b4e7f2a91c53
Create Date: 2026-04-11 18:52:45.953213

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15a13c99aaf1"
down_revision: Union[str, None] = "b4e7f2a91c53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language_profiles",
        sa.Column("iso_639_3", sa.String(length=3), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("autonym", sa.Text(), nullable=True),
        sa.Column("family", sa.Text(), nullable=True),
        sa.Column("branch", sa.Text(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("typology_summary", sa.Text(), nullable=True),
        sa.Column("morphology_notes", sa.Text(), nullable=True),
        sa.Column(
            "common_affixes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["iso_639_3"],
            ["iso_language.iso639"],
        ),
        sa.PrimaryKeyConstraint("iso_639_3"),
    )
    op.create_table(
        "language_morphemes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso_639_3", sa.String(length=3), nullable=False),
        sa.Column("morpheme", sa.Text(), nullable=False),
        sa.Column("morpheme_class", sa.Text(), nullable=False),
        sa.Column("first_seen_revision_id", sa.Integer(), nullable=True),
        sa.Column(
            "first_seen_at", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_revision_id"], ["bible_revision.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["iso_639_3"], ["language_profiles.iso_639_3"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "iso_639_3", "morpheme", name="uq_language_morphemes_iso_morpheme"
        ),
    )
    op.create_index(
        "ix_language_morphemes_iso", "language_morphemes", ["iso_639_3"], unique=False
    )
    op.create_index(
        "ix_language_morphemes_iso_class",
        "language_morphemes",
        ["iso_639_3", "morpheme_class"],
        unique=False,
    )
    op.create_table(
        "tokenizer_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso_639_3", sa.String(length=3), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("n_sample_verses", sa.Integer(), nullable=True),
        sa.Column("sample_method", sa.Text(), nullable=True),
        sa.Column("source_model", sa.Text(), nullable=True),
        sa.Column("stats_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), server_default="completed", nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["iso_639_3"], ["language_profiles.iso_639_3"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"], ["bible_revision.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tokenizer_runs_iso", "tokenizer_runs", ["iso_639_3"], unique=False
    )
    op.create_index(
        "ix_tokenizer_runs_revision", "tokenizer_runs", ["revision_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tokenizer_runs_revision", table_name="tokenizer_runs")
    op.drop_index("ix_tokenizer_runs_iso", table_name="tokenizer_runs")
    op.drop_table("tokenizer_runs")
    op.drop_index("ix_language_morphemes_iso_class", table_name="language_morphemes")
    op.drop_index("ix_language_morphemes_iso", table_name="language_morphemes")
    op.drop_table("language_morphemes")
    op.drop_table("language_profiles")
    # ### end Alembic commands ###
