"""add eflomal tables

Revision ID: 18a3718e95d8
Revises: eca4f540a198
Create Date: 2026-03-20 11:28:01.335467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18a3718e95d8"
down_revision: Union[str, None] = "eca4f540a198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eflomal_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("num_verse_pairs", sa.Integer(), nullable=True),
        sa.Column("num_alignment_links", sa.Integer(), nullable=True),
        sa.Column("num_dictionary_entries", sa.Integer(), nullable=True),
        sa.Column("num_missing_words", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id"),
    )
    op.create_table(
        "eflomal_cooccurrence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("source_word", sa.String(), nullable=False),
        sa.Column("target_word", sa.String(), nullable=False),
        sa.Column("co_occur_count", sa.Integer(), nullable=False),
        sa.Column("aligned_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["eflomal_model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_eflomal_cooccurrence_lookup",
        "eflomal_cooccurrence",
        ["model_id", "source_word", "target_word"],
        unique=False,
    )
    op.create_table(
        "eflomal_dictionary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("source_word", sa.String(), nullable=False),
        sa.Column("target_word", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["eflomal_model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_eflomal_dictionary_model_source",
        "eflomal_dictionary",
        ["model_id", "source_word"],
        unique=False,
    )
    op.create_index(
        "ux_eflomal_dictionary_model_source_target",
        "eflomal_dictionary",
        ["model_id", "source_word", "target_word"],
        unique=True,
    )
    op.create_table(
        "eflomal_target_word_count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["eflomal_model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ux_eflomal_target_word_count_model_word",
        "eflomal_target_word_count",
        ["model_id", "word"],
        unique=True,
    )
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence", table_name="agent_lexeme_cards"
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", "confidence"],
        unique=False,
        postgresql_ops={"confidence": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence",
        table_name="agent_lexeme_cards",
        postgresql_ops={"confidence": "DESC"},
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", sa.text("confidence DESC")],
        unique=False,
    )
    op.drop_index(
        "ux_eflomal_target_word_count_model_word",
        table_name="eflomal_target_word_count",
    )
    op.drop_table("eflomal_target_word_count")
    op.drop_index(
        "ux_eflomal_dictionary_model_source_target", table_name="eflomal_dictionary"
    )
    op.drop_index("ix_eflomal_dictionary_model_source", table_name="eflomal_dictionary")
    op.drop_table("eflomal_dictionary")
    op.drop_index("ix_eflomal_cooccurrence_lookup", table_name="eflomal_cooccurrence")
    op.drop_table("eflomal_cooccurrence")
    op.drop_table("eflomal_model")
    # ### end Alembic commands ###
