"""add verse_morpheme_index table

Revision ID: 1fe4e7b897b4
Revises: 15a13c99aaf1
Create Date: 2026-04-13 14:35:08.538829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe4e7b897b4'
down_revision: Union[str, None] = '15a13c99aaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse_morpheme_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_text_id', sa.Integer(), nullable=False),
    sa.Column('morpheme_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('surface_forms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['morpheme_id'], ['language_morphemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_text_id'], ['verse_text.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verse_text_id', 'morpheme_id', name='uq_verse_morpheme')
    )
    op.create_index('ix_verse_morpheme_index_morpheme', 'verse_morpheme_index', ['morpheme_id'], unique=False)
    op.create_index('ix_verse_morpheme_index_verse', 'verse_morpheme_index', ['verse_text_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verse_morpheme_index_verse', table_name='verse_morpheme_index')
    op.drop_index('ix_verse_morpheme_index_morpheme', table_name='verse_morpheme_index')
    op.drop_table('verse_morpheme_index')
    # ### end Alembic commands ###
