"""my migration

Revision ID: 1ffbe853c436
Revises: 803f2285c78c
Create Date: 2024-02-05 15:58:02.803007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffbe853c436'
down_revision: Union[str, None] = '803f2285c78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_text', sa.Column('revision_id', sa.Integer(), nullable=True))
    op.drop_constraint('verse_text_bible_revision_id_fkey', 'verse_text', type_='foreignkey')
    op.create_foreign_key(None, 'verse_text', 'bible_revision', ['revision_id'], ['id'])
    op.drop_column('verse_text', 'bible_revision_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_text', sa.Column('bible_revision_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'verse_text', type_='foreignkey')
    op.create_foreign_key('verse_text_bible_revision_id_fkey', 'verse_text', 'bible_revision', ['bible_revision_id'], ['id'])
    op.drop_column('verse_text', 'revision_id')
    # ### end Alembic commands ###
