"""add indexes to agent tables for query optimization

Revision ID: 29939a4687c1
Revises: 49d73218fbc2
Create Date: 2025-10-21 20:48:28.221674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29939a4687c1"
down_revision: Union[str, None] = "49d73218fbc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", "confidence"],
        unique=False,
        postgresql_ops={"confidence": "DESC"},
    )
    op.create_index(
        "ix_agent_lexeme_cards_surface_forms",
        "agent_lexeme_cards",
        ["surface_forms"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_agent_word_alignments_lang_source",
        "agent_word_alignments",
        ["source_language", "target_language", "source_word"],
        unique=False,
    )
    op.create_index(
        "ix_agent_word_alignments_lang_target",
        "agent_word_alignments",
        ["source_language", "target_language", "target_word"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Manually add functional index for case-insensitive target_lemma searches (can't be auto-generated)
    op.execute(
        "CREATE INDEX ix_agent_lexeme_cards_target_lemma_lower "
        "ON agent_lexeme_cards (LOWER(target_lemma))"
    )


def downgrade() -> None:
    # Manually drop functional index
    op.drop_index(
        "ix_agent_lexeme_cards_target_lemma_lower", table_name="agent_lexeme_cards"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_agent_word_alignments_lang_target", table_name="agent_word_alignments"
    )
    op.drop_index(
        "ix_agent_word_alignments_lang_source", table_name="agent_word_alignments"
    )
    op.drop_index(
        "ix_agent_lexeme_cards_surface_forms",
        table_name="agent_lexeme_cards",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence",
        table_name="agent_lexeme_cards",
        postgresql_ops={"confidence": "DESC"},
    )
    # ### end Alembic commands ###
