"""fix

Revision ID: 2c1eeb52f8ff
Revises: e32e60778e91
Create Date: 2024-01-19 17:48:45.615704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1eeb52f8ff'
down_revision: Union[str, None] = 'e32e60778e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bible_revision_back_translation_id_fkey', 'bible_revision', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('bible_revision_back_translation_id_fkey', 'bible_revision', 'bible_version', ['back_translation_id'], ['id'])
    # ### end Alembic commands ###
