"""Add index for user_id in user_groups

Revision ID: 2d4fcff5485c
Revises: 661323a8c136
Create Date: 2025-04-22 12:55:02.965801

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d4fcff5485c"
down_revision: Union[str, None] = "661323a8c136"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_group_user_id", "user_groups", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_group_user_id", table_name="user_groups")
    # ### end Alembic commands ###
