"""Add indexes for performance on assessment_result

Revision ID: 3673c2daee16
Revises: 36152cdb4af0
Create Date: 2025-04-22 12:26:13.019441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3673c2daee16"
down_revision: Union[str, None] = "36152cdb4af0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "alignment_threshold_scores_assessment_id_idx",
        table_name="alignment_threshold_scores",
    )
    op.drop_index(
        "alignment_threshold_scores_vref_idx", table_name="alignment_threshold_scores"
    )
    op.create_index(
        "idx_assessment_id", "assessment_result", ["assessment_id"], unique=False
    )
    op.create_index(
        "idx_assessment_result_main",
        "assessment_result",
        ["assessment_id", "book", "chapter", "verse", "id"],
        unique=False,
    )
    op.create_index(
        "idx_book_chapter_verse",
        "assessment_result",
        ["book", "chapter", "verse"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_book_chapter_verse", table_name="assessment_result")
    op.drop_index("idx_assessment_result_main", table_name="assessment_result")
    op.drop_index("idx_assessment_id", table_name="assessment_result")
    op.create_index(
        "alignment_threshold_scores_vref_idx",
        "alignment_threshold_scores",
        ["vref"],
        unique=False,
    )
    op.create_index(
        "alignment_threshold_scores_assessment_id_idx",
        "alignment_threshold_scores",
        ["assessment_id"],
        unique=False,
    )
    # ### end Alembic commands ###
