"""Add indexes for version access filtering

Revision ID: 4028298943fc
Revises: 3673c2daee16
Create Date: 2025-04-22 12:38:51.553683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4028298943fc"
down_revision: Union[str, None] = "3673c2daee16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_bible_version_deleted", "bible_version", ["deleted"], unique=False
    )
    op.create_index(
        "ix_bible_version_access_group",
        "bible_version_access",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        "ix_bible_version_access_version",
        "bible_version_access",
        ["bible_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_bible_version_access_version_group",
        "bible_version_access",
        ["bible_version_id", "group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_bible_version_access_version_group", table_name="bible_version_access"
    )
    op.drop_index("ix_bible_version_access_version", table_name="bible_version_access")
    op.drop_index("ix_bible_version_access_group", table_name="bible_version_access")
    op.drop_index("ix_bible_version_deleted", table_name="bible_version")
    # ### end Alembic commands ###
