"""Add agent_lexeme_cards and agent_word_alignments tables

Revision ID: 49d73218fbc2
Revises: 56ea180ef143
Create Date: 2025-10-21 20:07:18.068687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49d73218fbc2"
down_revision: Union[str, None] = "56ea180ef143"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_lexeme_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_lemma", sa.Text(), nullable=True),
        sa.Column("target_lemma", sa.Text(), nullable=False),
        sa.Column("source_language", sa.String(length=3), nullable=True),
        sa.Column("target_language", sa.String(length=3), nullable=True),
        sa.Column("pos", sa.Text(), nullable=True),
        sa.Column(
            "surface_forms", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("senses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("examples", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("last_updated", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_language"],
            ["iso_language.iso639"],
        ),
        sa.ForeignKeyConstraint(
            ["target_language"],
            ["iso_language.iso639"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_lexeme_cards_unique",
        "agent_lexeme_cards",
        ["source_lemma", "target_lemma", "source_language", "target_language"],
        unique=True,
    )
    op.create_table(
        "agent_word_alignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_word", sa.Text(), nullable=False),
        sa.Column("target_word", sa.Text(), nullable=False),
        sa.Column("source_language", sa.String(length=3), nullable=True),
        sa.Column("target_language", sa.String(length=3), nullable=True),
        sa.Column("is_human_verified", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("last_updated", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_language"],
            ["iso_language.iso639"],
        ),
        sa.ForeignKeyConstraint(
            ["target_language"],
            ["iso_language.iso639"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_word_alignments")
    op.drop_index("ix_agent_lexeme_cards_unique", table_name="agent_lexeme_cards")
    op.drop_table("agent_lexeme_cards")
    # ### end Alembic commands ###
