"""tp-fix migration

Revision ID: 56ea180ef143
Revises: d2b0538c6bd5
Create Date: 2025-09-24 08:14:42.593760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ea180ef143'
down_revision: Union[str, None] = 'd2b0538c6bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_lengths_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('vref', sa.Text(), nullable=True),
    sa.Column('word_lengths', sa.Numeric(), nullable=True),
    sa.Column('char_lengths', sa.Numeric(), nullable=True),
    sa.Column('word_lengths_z', sa.Numeric(), nullable=True),
    sa.Column('char_lengths_z', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['vref'], ['verse_reference.full_verse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_lengths_table_assessment_id'), 'text_lengths_table', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_text_lengths_table_vref'), 'text_lengths_table', ['vref'], unique=False)
    op.drop_index('ix_text_proportions_table_assessment_id', table_name='text_proportions_table')
    op.drop_index('ix_text_proportions_table_vref', table_name='text_proportions_table')
    op.drop_table('text_proportions_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_proportions_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('word_proportions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('char_proportions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('word_proportions_z', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('char_proportions_z', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name='text_proportions_table_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['vref'], ['verse_reference.full_verse_id'], name='text_proportions_table_vref_fkey'),
    sa.PrimaryKeyConstraint('id', name='text_proportions_table_pkey')
    )
    op.create_index('ix_text_proportions_table_vref', 'text_proportions_table', ['vref'], unique=False)
    op.create_index('ix_text_proportions_table_assessment_id', 'text_proportions_table', ['assessment_id'], unique=False)
    op.drop_index(op.f('ix_text_lengths_table_vref'), table_name='text_lengths_table')
    op.drop_index(op.f('ix_text_lengths_table_assessment_id'), table_name='text_lengths_table')
    op.drop_table('text_lengths_table')
    # ### end Alembic commands ###
