"""Add agent critique issue table with resolution tracking

Revision ID: 5705d0be0143
Revises: 2eccf09f725c
Create Date: 2025-10-30 07:32:41.232798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5705d0be0143"
down_revision: Union[str, None] = "2eccf09f725c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_critique_issue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("vref", sa.String(length=20), nullable=False),
        sa.Column("book", sa.String(length=10), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("verse", sa.Integer(), nullable=False),
        sa.Column("issue_type", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("resolved_by_id", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), nullable=True, server_default=sa.text("now()")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_critique_issue_assessment",
        "agent_critique_issue",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_book_chapter_verse",
        "agent_critique_issue",
        ["book", "chapter", "verse"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_resolved",
        "agent_critique_issue",
        ["is_resolved"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_resolved_by",
        "agent_critique_issue",
        ["resolved_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_severity",
        "agent_critique_issue",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_type",
        "agent_critique_issue",
        ["issue_type"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_vref", "agent_critique_issue", ["vref"], unique=False
    )
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence", table_name="agent_lexeme_cards"
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", "confidence"],
        unique=False,
        postgresql_ops={"confidence": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence",
        table_name="agent_lexeme_cards",
        postgresql_ops={"confidence": "DESC"},
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", sa.text("confidence DESC")],
        unique=False,
    )
    op.drop_index("ix_agent_critique_issue_vref", table_name="agent_critique_issue")
    op.drop_index("ix_agent_critique_issue_type", table_name="agent_critique_issue")
    op.drop_index("ix_agent_critique_issue_severity", table_name="agent_critique_issue")
    op.drop_index(
        "ix_agent_critique_issue_resolved_by", table_name="agent_critique_issue"
    )
    op.drop_index("ix_agent_critique_issue_resolved", table_name="agent_critique_issue")
    op.drop_index(
        "ix_agent_critique_issue_book_chapter_verse", table_name="agent_critique_issue"
    )
    op.drop_index(
        "ix_agent_critique_issue_assessment", table_name="agent_critique_issue"
    )
    op.drop_table("agent_critique_issue")
    # ### end Alembic commands ###
