"""Add indexes for bible_revision filtering

Revision ID: 661323a8c136
Revises: 4028298943fc
Create Date: 2025-04-22 12:44:34.320826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "661323a8c136"
down_revision: Union[str, None] = "4028298943fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_bible_revision_deleted", "bible_revision", ["deleted"], unique=False
    )
    op.create_index(
        "ix_bible_revision_version_id",
        "bible_revision",
        ["bible_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bible_revision_version_id", table_name="bible_revision")
    op.drop_index("ix_bible_revision_deleted", table_name="bible_revision")
    # ### end Alembic commands ###
