"""my migration

Revision ID: 66333edc6c6d
Revises: 0f6ea0dbb994
Create Date: 2024-01-19 17:28:31.137083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66333edc6c6d'
down_revision: Union[str, None] = '0f6ea0dbb994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'iso_language', ['iso639'])
    op.create_unique_constraint(None, 'iso_script', ['iso15924'])
    op.create_unique_constraint(None, 'verse_reference', ['full_verse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verse_reference', type_='unique')
    op.drop_constraint(None, 'iso_script', type_='unique')
    op.drop_constraint(None, 'iso_language', type_='unique')
    # ### end Alembic commands ###
