"""Add index on verse_text.revision_id

Revision ID: 6fca538ef46c
Revises: 2d4fcff5485c
Create Date: 2025-04-22 22:54:34.742599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fca538ef46c'
down_revision: Union[str, None] = '2d4fcff5485c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_verse_text_revision_id', 'verse_text', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verse_text_revision_id', table_name='verse_text')
    # ### end Alembic commands ###
