"""Add field is reference in bible version

Revision ID: 708864ea5311
Revises: a566a8aefc6c
Create Date: 2024-05-09 08:55:19.542455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708864ea5311'
down_revision: Union[str, None] = 'a566a8aefc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bible_version', sa.Column('is_reference', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bible_version', 'is_reference')
    # ### end Alembic commands ###
