"""add TfidfPcaVector and TextProportionsTable model

Revision ID: 7b250817a39a
Revises: 2d4fcff5485c
Create Date: 2025-06-18 12:39:03.290769

"""
from typing import Sequence, Union
import pgvector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b250817a39a'
down_revision: Union[str, None] = '2d4fcff5485c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_proportions_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('vref', sa.Text(), nullable=True),
    sa.Column('word_proportions', sa.Numeric(), nullable=True),
    sa.Column('char_proportions', sa.Numeric(), nullable=True),
    sa.Column('word_proportions_z', sa.Numeric(), nullable=True),
    sa.Column('char_proportions_z', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['vref'], ['verse_reference.full_verse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_proportions_table_assessment_id'), 'text_proportions_table', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_text_proportions_table_vref'), 'text_proportions_table', ['vref'], unique=False)
    op.create_table('tfidf_pca_vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('vref', sa.Text(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=300), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['vref'], ['verse_reference.full_verse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tfidf_pca_vector_assessment_id'), 'tfidf_pca_vector', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_tfidf_pca_vector_vref'), 'tfidf_pca_vector', ['vref'], unique=False)
    op.drop_index('ix_verse_text_revision_book', table_name='verse_text')
    op.drop_index('ix_verse_text_revision_id', table_name='verse_text')
    op.drop_index('ix_verse_text_verse_reference_revision', table_name='verse_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_verse_text_verse_reference_revision', 'verse_text', ['verse_reference', 'revision_id'], unique=False)
    op.create_index('ix_verse_text_revision_id', 'verse_text', ['revision_id'], unique=False)
    op.create_index('ix_verse_text_revision_book', 'verse_text', ['revision_id', 'book'], unique=False)
    op.drop_index(op.f('ix_tfidf_pca_vector_vref'), table_name='tfidf_pca_vector')
    op.drop_index(op.f('ix_tfidf_pca_vector_assessment_id'), table_name='tfidf_pca_vector')
    op.drop_table('tfidf_pca_vector')
    op.drop_index(op.f('ix_text_proportions_table_vref'), table_name='text_proportions_table')
    op.drop_index(op.f('ix_text_proportions_table_assessment_id'), table_name='text_proportions_table')
    op.drop_table('text_proportions_table')
    # ### end Alembic commands ###
