"""my migration

Revision ID: 7fc1d21c46de
Revises: 446ff3a380bd
Create Date: 2024-01-25 16:55:28.567204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc1d21c46de'
down_revision: Union[str, None] = '446ff3a380bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bible_revision', 'bible_revision', ['back_translation_id'], ['id'])
    op.create_foreign_key(None, 'bible_version', 'bible_version', ['back_translation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bible_version', type_='foreignkey')
    op.drop_constraint(None, 'bible_revision', type_='foreignkey')
    # ### end Alembic commands ###
