"""add source_target_language_to_eflomal_assessment

Revision ID: 853836b576a0
Revises: 92d7a5b3de0c
Create Date: 2026-03-27 14:39:06.423885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '853836b576a0'
down_revision: Union[str, None] = '92d7a5b3de0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eflomal_model')
    op.drop_index('ix_agent_lexeme_cards_lang_confidence', table_name='agent_lexeme_cards')
    op.create_index('ix_agent_lexeme_cards_lang_confidence', 'agent_lexeme_cards', ['source_language', 'target_language', 'confidence'], unique=False, postgresql_ops={'confidence': 'DESC'})
    op.create_unique_constraint(None, 'iso_language', ['iso639'])
    op.create_unique_constraint(None, 'iso_script', ['iso15924'])
    op.create_unique_constraint(None, 'verse_reference', ['full_verse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verse_reference', type_='unique')
    op.drop_constraint(None, 'iso_script', type_='unique')
    op.drop_constraint(None, 'iso_language', type_='unique')
    op.drop_index('ix_agent_lexeme_cards_lang_confidence', table_name='agent_lexeme_cards', postgresql_ops={'confidence': 'DESC'})
    op.create_index('ix_agent_lexeme_cards_lang_confidence', 'agent_lexeme_cards', ['source_language', 'target_language', sa.text('confidence DESC')], unique=False)
    op.create_table('eflomal_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artifact_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_verse_pairs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_alignment_links', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_dictionary_entries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_missing_words', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name='eflomal_model_assessment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='eflomal_model_pkey'),
    sa.UniqueConstraint('assessment_id', name='eflomal_model_assessment_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
