"""drop eflomal_cooccurrence table

Revision ID: 91243bb07389
Revises: 7adc82ec084a
Create Date: 2026-06-03 15:34:55.055274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91243bb07389"
down_revision: Union[str, None] = "7adc82ec084a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_eflomal_cooccurrence_lookup", table_name="eflomal_cooccurrence")
    op.drop_table("eflomal_cooccurrence")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eflomal_cooccurrence",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("assessment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source_word", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("target_word", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("co_occur_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("aligned_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["eflomal_assessment.id"],
            name="eflomal_cooccurrence_assessment_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="eflomal_cooccurrence_pkey"),
    )
    op.create_index(
        "ix_eflomal_cooccurrence_lookup",
        "eflomal_cooccurrence",
        ["assessment_id", "source_word", "target_word"],
        unique=False,
    )
    # ### end Alembic commands ###
