"""add eflomal src and tgt languages

Revision ID: 92d7a5b3de0c
Revises: 0858bc754cc3
Create Date: 2026-03-27 13:51:56.002309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92d7a5b3de0c"
down_revision: Union[str, None] = "0858bc754cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence", table_name="agent_lexeme_cards"
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", "confidence"],
        unique=False,
        postgresql_ops={"confidence": "DESC"},
    )
    op.add_column(
        "eflomal_assessment",
        sa.Column("source_language", sa.String(length=3), nullable=True),
    )
    op.add_column(
        "eflomal_assessment",
        sa.Column("target_language", sa.String(length=3), nullable=True),
    )
    op.create_index(
        "ix_eflomal_assessment_language_pair",
        "eflomal_assessment",
        ["source_language", "target_language"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_eflomal_assessment_language_pair", table_name="eflomal_assessment"
    )
    op.drop_column("eflomal_assessment", "target_language")
    op.drop_column("eflomal_assessment", "source_language")
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence",
        table_name="agent_lexeme_cards",
        postgresql_ops={"confidence": "DESC"},
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", sa.text("confidence DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
