"""Add ivfflat index to tfidf_pca_vector

Revision ID: a022f5ed53e4
Revises: df16e9799966
Create Date: 2025-07-10 13:57:32.862398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a022f5ed53e4"
down_revision: Union[str, None] = "df16e9799966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "tfidf_pca_vector_ivfflat_idx",
        "tfidf_pca_vector",
        ["vector"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_ops={"vector": "vector_ip_ops"},
        postgresql_with={"lists": "100"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "tfidf_pca_vector_ivfflat_idx",
        table_name="tfidf_pca_vector",
        postgresql_using="ivfflat",
        postgresql_ops={"vector": "vector_ip_ops"},
        postgresql_with={"lists": "100"},
    )
    # ### end Alembic commands ###
