"""add book chapter and verse to Score tables

Revision ID: ae6c8e7a2998
Revises: e16e19bf05be
Create Date: 2024-03-08 11:54:29.311341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae6c8e7a2998"
down_revision: Union[str, None] = "e16e19bf05be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alignment_threshold_scores", sa.Column("book", sa.Text(), nullable=True)
    )
    op.add_column(
        "alignment_threshold_scores", sa.Column("chapter", sa.Integer(), nullable=True)
    )
    op.add_column(
        "alignment_threshold_scores", sa.Column("verse", sa.Integer(), nullable=True)
    )
    op.add_column(
        "alignment_top_source_scores", sa.Column("book", sa.Text(), nullable=True)
    )
    op.add_column(
        "alignment_top_source_scores", sa.Column("chapter", sa.Integer(), nullable=True)
    )
    op.add_column(
        "alignment_top_source_scores", sa.Column("verse", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(None, "iso_language", ["iso639"])
    op.create_unique_constraint(None, "iso_script", ["iso15924"])
    op.create_unique_constraint(None, "verse_reference", ["full_verse_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verse_reference", type_="unique")
    op.drop_constraint(None, "iso_script", type_="unique")
    op.drop_constraint(None, "iso_language", type_="unique")
    op.drop_column("alignment_top_source_scores", "verse")
    op.drop_column("alignment_top_source_scores", "chapter")
    op.drop_column("alignment_top_source_scores", "book")
    op.drop_column("alignment_threshold_scores", "verse")
    op.drop_column("alignment_threshold_scores", "chapter")
    op.drop_column("alignment_threshold_scores", "book")
    # ### end Alembic commands ###
