"""Add indexes for assessment and alignment score queries

Revision ID: b063bf145187
Revises: efb86c2fbf71
Create Date: 2025-04-22 23:02:15.482947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b063bf145187'
down_revision: Union[str, None] = 'efb86c2fbf71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alignment_scores_assessment_score', 'alignment_top_source_scores', ['assessment_id', 'score'], unique=False)
    op.create_index('ix_alignment_scores_grouping', 'alignment_top_source_scores', ['book', 'chapter', 'verse', 'source'], unique=False)
    op.create_index('ix_assessment_rev_ref_type_status_end', 'assessment', ['revision_id', 'reference_id', 'type', 'status', 'end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessment_rev_ref_type_status_end', table_name='assessment')
    op.drop_index('ix_alignment_scores_grouping', table_name='alignment_top_source_scores')
    op.drop_index('ix_alignment_scores_assessment_score', table_name='alignment_top_source_scores')
    # ### end Alembic commands ###
