"""add owner to version

Revision ID: b98383088ef3
Revises: f017febab52e
Create Date: 2024-03-04 17:00:47.226414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98383088ef3'
down_revision: Union[str, None] = 'f017febab52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bible_version', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bible_version', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint(None, 'iso_language', ['iso639'])
    op.create_unique_constraint(None, 'iso_script', ['iso15924'])
    op.create_unique_constraint(None, 'verse_reference', ['full_verse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verse_reference', type_='unique')
    op.drop_constraint(None, 'iso_script', type_='unique')
    op.drop_constraint(None, 'iso_language', type_='unique')
    op.drop_constraint(None, 'bible_version', type_='foreignkey')
    op.drop_column('bible_version', 'owner_id')
    # ### end Alembic commands ###
