"""owner_id field added to assessment

Revision ID: c3998d68f8f5
Revises: 708864ea5311
Create Date: 2024-05-15 09:45:16.867726

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3998d68f8f5"
down_revision: Union[str, None] = "708864ea5311"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assessment", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "assessment", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assessment", type_="foreignkey")
    op.drop_column("assessment", "owner_id")
    # ### end Alembic commands ###
