"""drop unused tfidf_pca_vector ivfflat index

Revision ID: ccdba9bec96d
Revises: b720f1c8a4d2
Create Date: 2026-09-17 12:04:12.142858

`tfidf_pca_vector_ivfflat_idx` is 246 GB — 19.4% of the 1,268 GB database — and
`pg_stat_user_indexes.idx_scan` reports 0 scans across 54 days of production
statistics. Its two btree siblings on the same table served 73,638 scans
(`assessment_id`) and 3,163 (`vref`) over that window, so the table is busy; it
is this index specifically that nothing reaches.

EXPLAIN against live data shows why. Every vector query the API issues carries a
`WHERE assessment_id = :id` filter, and with that filter the planner takes
`ix_tfidf_pca_vector_assessment_id` plus a top-N heapsort (~60 ms) and never
touches the ivfflat index. Only removing the filter makes it switch. So the
index is eligible and simply never the cheaper plan.

Dropping it takes tfidf_pca_vector from 499 GB to ~253 GB and the database from
~1,268 GB to ~1,022 GB.

CONCURRENTLY is used because a plain DROP INDEX needs ACCESS EXCLUSIVE on
tfidf_pca_vector. The drop itself is quick — a catalog change plus unlinking
files — but acquiring that lock means waiting for in-flight queries to finish
while every new query queues behind it. On a table serving 73,638 index scans
that stall is the risk worth avoiding, not the drop. DROP INDEX CONCURRENTLY
cannot run inside the transaction Alembic wraps migrations in, hence
autocommit_block(); the same shape as
7f2e9a4b8c31_add_pg_trgm_index_on_verse_text.py.

See #971.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccdba9bec96d"
down_revision: Union[str, None] = "b720f1c8a4d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # IF EXISTS keeps this retryable. An interrupted DROP INDEX CONCURRENTLY can
    # leave the index present but marked invalid; re-running the migration then
    # finishes the job rather than erroring on a half-dropped object.
    with op.get_context().autocommit_block():
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS tfidf_pca_vector_ivfflat_idx")


def downgrade() -> None:
    """Rebuild the index exactly as it was — which is not a practical rollback.

    Two things about this are worth stating before anyone runs it.

    **It takes hours, not a moment.** CREATE INDEX CONCURRENTLY over ~193 M
    300-dimensional vectors on db.m5.large (2 vCPU, maintenance_work_mem 124 MB,
    max_parallel_maintenance_workers 2) is a long build. "Rebuildable in one
    command" is true about risk and false about time. If the drop turns out to be
    wrong, the answer is a planned rebuild, not `alembic downgrade`.

    **lists = 100 is deliberately preserved, and is also wrong.** It was
    undersized for 193 M rows — pgvector's guidance is sqrt(rows) above 1 M, so
    ~13,900. It is kept anyway because a downgrade's job is to put the schema back
    the way it was, and one that quietly builds a *different* object than upgrade
    removed is worse than none: it looks like it worked. So if you actually want
    an ANN index on this table, do not reach for this function — build one
    deliberately at ~13,900 lists, or use HNSW.

    vector_ip_ops is spelled out because omitting it does not mean "the default we
    had". pgvector's default opclass is vector_l2_ops, so leaving it off rebuilds
    an L2-distance index where an inner-product one was dropped — hours of work
    for an index the `<#>` queries cannot use. Alembic's own autogenerated
    downgrade for this change dropped it.
    """
    with op.get_context().autocommit_block():
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS tfidf_pca_vector_ivfflat_idx "
            "ON tfidf_pca_vector USING ivfflat (vector vector_ip_ops) "
            "WITH (lists = 100)"
        )
