"""second_migration_add_index_to_ngrams

Revision ID: d2b0538c6bd5
Revises: 88bbc63b45ea
Create Date: 2025-09-15 15:28:22.054972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2b0538c6bd5"
down_revision: Union[str, None] = "88bbc63b45ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "iso_language", ["iso639"])
    op.create_unique_constraint(None, "iso_script", ["iso15924"])
    op.create_index(
        op.f("ix_ngram_vref_table_ngram_id"),
        "ngram_vref_table",
        ["ngram_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ngrams_table_assessment_id"),
        "ngrams_table",
        ["assessment_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "verse_reference", ["full_verse_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verse_reference", type_="unique")
    op.drop_index(op.f("ix_ngrams_table_assessment_id"), table_name="ngrams_table")
    op.drop_index(op.f("ix_ngram_vref_table_ngram_id"), table_name="ngram_vref_table")
    op.drop_constraint(None, "iso_script", type_="unique")
    op.drop_constraint(None, "iso_language", type_="unique")
    # ### end Alembic commands ###
