"""ngrams integration

Revision ID: df16e9799966
Revises: 7b250817a39a
Create Date: 2025-06-24 14:33:53.117790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df16e9799966"
down_revision: Union[str, None] = "7b250817a39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_alignment_scores_assessment_score",
        "alignment_top_source_scores",
        ["assessment_id", "score"],
        unique=False,
    )
    op.create_index(
        "ix_alignment_scores_grouping",
        "alignment_top_source_scores",
        ["book", "chapter", "verse", "source"],
        unique=False,
    )
    op.create_index(
        "ix_assessment_rev_ref_type_status_end",
        "assessment",
        ["revision_id", "reference_id", "type", "status", "end_time"],
        unique=False,
    )
    op.create_index(
        "ix_verse_text_revision_book",
        "verse_text",
        ["revision_id", "book"],
        unique=False,
    )
    op.create_index(
        "ix_verse_text_revision_id", "verse_text", ["revision_id"], unique=False
    )
    op.create_index(
        "ix_verse_text_verse_reference_revision",
        "verse_text",
        ["verse_reference", "revision_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verse_text_verse_reference_revision", table_name="verse_text")
    op.drop_index("ix_verse_text_revision_id", table_name="verse_text")
    op.drop_index("ix_verse_text_revision_book", table_name="verse_text")
    op.drop_index("ix_assessment_rev_ref_type_status_end", table_name="assessment")
    op.drop_index(
        "ix_alignment_scores_grouping", table_name="alignment_top_source_scores"
    )
    op.drop_index(
        "ix_alignment_scores_assessment_score", table_name="alignment_top_source_scores"
    )
    # ### end Alembic commands ###
