"""add nullable owner to version

Revision ID: e16e19bf05be
Revises: f017febab52e
Create Date: 2024-03-07 07:44:58.170276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e16e19bf05be"
down_revision: Union[str, None] = "f017febab52e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bible_version", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "bible_version", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bible_version", type_="foreignkey")
    op.drop_column("bible_version", "owner_id")
    # ### end Alembic commands ###
