"""Add verse_text indexes on (revision_id, book) and (verse_reference, revision_id)

Revision ID: efb86c2fbf71
Revises: 6fca538ef46c
Create Date: 2025-04-22 22:59:23.491006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb86c2fbf71'
down_revision: Union[str, None] = '6fca538ef46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_verse_text_revision_book', 'verse_text', ['revision_id', 'book'], unique=False)
    op.create_index('ix_verse_text_verse_reference_revision', 'verse_text', ['verse_reference', 'revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verse_text_verse_reference_revision', table_name='verse_text')
    op.drop_index('ix_verse_text_revision_book', table_name='verse_text')
    # ### end Alembic commands ###
