"""assessment access removed

Revision ID: f641e70baa2e
Revises: c3998d68f8f5
Create Date: 2024-07-02 17:47:25.361735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f641e70baa2e'
down_revision: Union[str, None] = 'c3998d68f8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_access',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name='assessment_access_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='assessment_access_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_access_pkey')
    )
    # ### end Alembic commands ###
