"""add agent_critique_issue table

Revision ID: f75fd7a66f6d
Revises: 2eccf09f725c
Create Date: 2025-10-28 20:20:55.164682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f75fd7a66f6d"
down_revision: Union[str, None] = "2eccf09f725c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_critique_issue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("vref", sa.String(length=20), nullable=False),
        sa.Column("book", sa.String(length=10), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("verse", sa.Integer(), nullable=False),
        sa.Column("issue_type", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_critique_issue_assessment",
        "agent_critique_issue",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_book_chapter_verse",
        "agent_critique_issue",
        ["book", "chapter", "verse"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_severity",
        "agent_critique_issue",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_type",
        "agent_critique_issue",
        ["issue_type"],
        unique=False,
    )
    op.create_index(
        "ix_agent_critique_issue_vref", "agent_critique_issue", ["vref"], unique=False
    )
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence", table_name="agent_lexeme_cards"
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", "confidence"],
        unique=False,
        postgresql_ops={"confidence": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_agent_lexeme_cards_lang_confidence",
        table_name="agent_lexeme_cards",
        postgresql_ops={"confidence": "DESC"},
    )
    op.create_index(
        "ix_agent_lexeme_cards_lang_confidence",
        "agent_lexeme_cards",
        ["source_language", "target_language", sa.text("confidence DESC")],
        unique=False,
    )
    op.drop_index("ix_agent_critique_issue_vref", table_name="agent_critique_issue")
    op.drop_index("ix_agent_critique_issue_type", table_name="agent_critique_issue")
    op.drop_index("ix_agent_critique_issue_severity", table_name="agent_critique_issue")
    op.drop_index(
        "ix_agent_critique_issue_book_chapter_verse", table_name="agent_critique_issue"
    )
    op.drop_index(
        "ix_agent_critique_issue_assessment", table_name="agent_critique_issue"
    )
    op.drop_table("agent_critique_issue")
    # ### end Alembic commands ###
