"""Initial migration

Revision ID: f9149ccd4822
Revises: 
Create Date: 2023-11-13 11:08:25.812111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9149ccd4822"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookReference",
        sa.Column("abbreviation", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("abbreviation"),
    )
    op.create_table(
        "isoLanguage",
        sa.Column("iso639", sa.String(length=3), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("iso639"),
        sa.UniqueConstraint("iso639"),
    )
    op.create_table(
        "isoScript",
        sa.Column("iso15924", sa.String(length=4), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("iso15924"),
        sa.UniqueConstraint("iso15924"),
    )
    op.create_table(
        "bibleVersion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("isoLanguage", sa.String(length=3), nullable=True),
        sa.Column("isoScript", sa.String(length=4), nullable=True),
        sa.Column("abbreviation", sa.Text(), nullable=True),
        sa.Column("rights", sa.Text(), nullable=True),
        sa.Column("forward_translation_id", sa.Integer(), nullable=True),
        sa.Column("back_translation_id", sa.Integer(), nullable=True),
        sa.Column("machine_translation", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["isoLanguage"],
            ["isoLanguage.iso639"],
        ),
        sa.ForeignKeyConstraint(
            ["isoScript"],
            ["isoScript.iso15924"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chapterReference",
        sa.Column("full_chapter_id", sa.Text(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("book_reference", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_reference"],
            ["bookReference.abbreviation"],
        ),
        sa.PrimaryKeyConstraint("full_chapter_id"),
    )
    op.create_table(
        "bibleRevision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("bible_version_id", sa.Integer(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("back_translation_id", sa.Integer(), nullable=True),
        sa.Column("machine_translation", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["back_translation_id"],
            ["bibleRevision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bible_version_id"],
            ["bibleVersion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "verseReference",
        sa.Column("full_verse_id", sa.Text(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("chapter", sa.Text(), nullable=True),
        sa.Column("book_reference", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_reference"],
            ["bookReference.abbreviation"],
        ),
        sa.ForeignKeyConstraint(
            ["chapter"],
            ["chapterReference.full_chapter_id"],
        ),
        sa.PrimaryKeyConstraint("full_verse_id"),
        sa.UniqueConstraint("full_verse_id"),
    )
    op.create_table(
        "assessment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("requested_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["bibleRevision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["bibleRevision.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "verseText",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("bible_revision_id", sa.Integer(), nullable=True),
        sa.Column("book", sa.Text(), nullable=True),
        sa.Column("chapter", sa.Integer(), nullable=True),
        sa.Column("verse", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bible_revision_id"],
            ["bibleRevision.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alignmentthresholdscores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("flag", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("vref", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("hide", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alignmentTopSourceScores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("flag", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("vref", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("hide", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assessmentResult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("flag", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("vref", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hide", sa.Boolean(), nullable=True),
        sa.Column("book", sa.Text(), nullable=True),
        sa.Column("chapter", sa.Integer(), nullable=True),
        sa.Column("verse", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assessmentResult")
    op.drop_table("alignmentTopSourceScores")
    op.drop_table("alignmentthresholdscores")
    op.drop_table("verseText")
    op.drop_table("assessment")
    op.drop_table("verseReference")
    op.drop_table("bibleRevision")
    op.drop_table("chapterReference")
    op.drop_table("bibleVersion")
    op.drop_table("isoScript")
    op.drop_table("isoLanguage")
    op.drop_table("bookReference")
    # ### end Alembic commands ###
