
name: branch-build

on:
  push:
    branches:
      - master

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Linting (Ruff)
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        ruff --ignore E501 --output-format=github .
      
    - name: Build API
      run: make build-actions
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
      
    - name: Test API
      run: make test
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        GRAPHQL_SECRET: ${{ secrets.GRAPHQL_SECRET }}
        AQUA_DB: ${{ secrets.AQUA_DB }}
        AQUA_URL: ${{ secrets.AQUA_URL }}
        TEST_KEY: ${{ secrets.TEST_KEY }}
        FAIL_KEY: ${{ secrets.FAIL_KEY }}
        KEY_VAULT: ${{ secrets.KEY_VAULT }}
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
        MODAL_WEBHOOK_TOKEN: ${{ secrets.MODAL_WEBHOOK_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push API
      run: make push-branch
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}

        
