
name: branch-build

on:
  push:
    branches:
      - master

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build API
      run: make build-actions
      
    - name: Test API
      run: make test
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        GRAPHQL_SECRET: ${{ secrets.GRAPHQL_SECRET }}
        AQUA_DB: ${{ secrets.AQUA_DB }}
        TEST_KEY: ${{ secrets.TEST_KEY }}
        FAIL_KEY: ${{ secrets.FAIL_KEY }}
        KEY_VAULT: ${{ secrets.KEY_VAULT }}

    - name: Build Pipelines
      run: make build-pipelines
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
        AQUA_DB: ${{ secrets.AQUA_DB }}
      
    - name: Test Pipelines
      run: make test-pipelines
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
        AQUA_DB: ${{ secrets.AQUA_DB }}

    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
        
    - name: Push API
      run: make push-branch

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.S3_SECRET }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Pipelines
      run: make push-pipelines
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}

    - name: Deploy API
      run: doctl app create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --force-rebuild
