
name: branch-build

on:
  push:
    branches:
      - master

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build 
      run: make build-actions
      
    - name: Test
      run: make test
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        GRAPHQL_SECRET: ${{ secrets.GRAPHQL_SECRET }}
      
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
        
    - name: Push 
      run: make push-branch

    - name: Deploy
      run: doctl app create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --force-rebuild
