name: branch-build

on:
  push:
    branches:
      - aws_new_backend

env:
  AWS_REGISTRY: 279795702643.dkr.ecr.us-east-1.amazonaws.com

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Linting (Ruff)
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install ruff
    #     ruff --ignore E501 --output-format=github .
      
    - name: Build API
      run: make build-actions
      env:
        REGISTRY: ${{ env.AWS_REGISTRY }}
      
    - name: Test API
      run: make test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push API
      run: make push-branch
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}

        
