name: branch-build

on:
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build API
      run: make build-actions
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
      
    - name: Test API
      run: make test
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        GRAPHQL_SECRET: ${{ secrets.GRAPHQL_SECRET }}
        AQUA_DB: ${{ secrets.AQUA_DB }}
        TEST_KEY: ${{ secrets.TEST_KEY }}
        FAIL_KEY: ${{ secrets.FAIL_KEY }}
        KEY_VAULT: ${{ secrets.KEY_VAULT }}
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
  
    - name: Linting 
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Run Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        ruff --format=github .

