name: branch-build

on:
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build 
      run: make build-actions
      
    - name: Test
      run: make test
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        GRAPHQL_SECRET: ${{ secrets.GRAPHQL_SECRET }}
        AQUA_DB: ${{ secrets.AQUA_DB }}
