name: branch-build

on:
  pull_request:
    branches:
      - release
      - main

jobs:

  tests:
    name: Building and pushing main branch images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Linting (Run Ruff)
      run: |
        python -m pip install --upgrade pip
        pip install isort
        pip install flake8
        isort --check .
        flake8 . --exclude='**/v1/**,**/v2/**,./venv,./alembic' --ignore=E501,W503,E203,E228,E226


    - name: Build API
      run: make build-actions
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}

    - name: Test API
      run: make test
